backend:
  name: github
  repo: zpthree/family-cookbook
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "recipe"
    label: "Recipes"
    folder: "src/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Slug (all lowercase; separate words with '-'; no spaces)", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Cook Time (includes prep)", name: "cookTime", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
